### ISSUE TITLE
PHP Fatal Error 

### ISSUE THREAD

**Issue by erdinctogulga** [kamalkhan/kk-star-ratings#112]
Fatal error: Uncaught Error: Class 'Bhittani\StarRating\classes\Stack' not found in /home/u9091456/public_html/wp-content/plugins/kk-star-ratings/src/classes/Migration.php:14 Stack trace: #0 /home/u9091456/public_html/wp-content/plugins/kk-star-ratings/src/functions/autoload.php(118): require_once() #1 /home/u9091456/public_html/wp-content/plugins/kk-star-ratings/src/config.php(40): Bhittani\StarRating\functions\autoload('Bhittani\\StarRa...', '/home/u9091456/...') #2 /home/u9091456/public_html/wp-content/plugins/kk-star-ratings/src/index.php(30): require('/home/u9091456/...') #3 /home/u9091456/public_html/wp-content/plugins/kk-star-ratings/index.php(33): require_once('/home/u9091456/...') #4 /home/u9091456/public_html/wp-admin/includes/plugin.php(2286): include_once('/home/u9091456/...') #5 /home/u9091456/public_html/wp-admin/plugins.php(191): plugin_sandbox_scrape('kk-star-ratings...') #6 {main} thrown in /home/u9091456/public_html/wp-content/plugins/kk-star-ratings/src/classes/Migration.php on line 14

On the new auto update, kk star rating PHP fatal error occurred

Version used PHP 7.4 - WordPress 5.8.1 running Dinova theme.
Operating system Linux
https://hadipisir.com

**Comment by MrAnssaien** [comment]
Same thing happened as soon as I manually updated to kk Star Rating v5.1.0. Disabled the plugin by renaming its folder for the moment. 

PHP version: 7.3.31 (Debian)
WordPress version: 5.8.1
Theme: Astra.

**Comment by MrAnssaien** [comment]
**UPDATE (temporary fix):** 

Adding this line: 
`require_once 'Stack.php';`
above `class Migration extends Stack` (line: 14) in Migration.php (found in: /wp-content/plugins/kk-star-ratings/src/classes/)
Fixed the issue.

**Comment by dcm20002000** [comment]
The same happend to me, and I was very happy with this plugin, so is graet when the problem it is fix and we can use it again. I have to rename the folder kk-star-ratings to desactivated the plugin and use my website. Thanks!

**Comment by dcm20002000** [comment]
I try what "MrAnssaien" said and it is not working for me, adding this line:
require_once 'Stack.php'; not fixed the issue, the plugin do not work and it is a pitty, I hope an update is coming soon,
Thank you.

**Comment by MrAnssaien** [comment]
> 
> 
> I try what "MrAnssaien" said and it is not working for me, adding this line: require_once 'Stack.php'; not fixed the issue, the plugin do not work and it is a pitty, I hope an update is coming soon, Thank you.

Try using the full path to Stack.php. 

Example (from OP's error log): 
require_once '/home/u9091456/public_html/wp-content/plugins/kk-star-ratings/src/classes/Stack.php';

**Comment by dcm20002000** [comment]
> > I try what "MrAnssaien" said and it is not working for me, adding this line: require_once 'Stack.php'; not fixed the issue, the plugin do not work and it is a pitty, I hope an update is coming soon, Thank you.
> 
> Try using the full path to Stack.php.
> 
> Example (from OP's error log): require_once '/home/u9091456/public_html/wp-content/plugins/kk-star-ratings/src/classes/Stack.php';

Thaks for your answer but I don`t understand, I go to Stack.php and then what?

**Comment by MrAnssaien** [comment]
> 
> 
> > > I try what "MrAnssaien" said and it is not working for me, adding this line: require_once 'Stack.php'; not fixed the issue, the plugin do not work and it is a pitty, I hope an update is coming soon, Thank you.
> > 
> > 
> > Try using the full path to Stack.php.
> > Example (from OP's error log): require_once '/home/u9091456/public_html/wp-content/plugins/kk-star-ratings/src/classes/Stack.php';
> 
> Thaks for your answer but I don`t understand, I go to Stack.php and then what?

You should go to Migration.php; not Stack.php. 
And then add: 

`require_once 'Stack.php'; ` above `class Migration extends Stack`

If you still get the same error, it means, you should add the full path to Stack.php.

**Comment by dcm20002000** [comment]
I try again with the full path and I get the error:

Warning: require_once(/home/u9091456/public_html/wp-content/plugins/kk-star-ratings/src/classes/Stack.php): failed to open stream: No such file or directory in /home/condoscojines/public_html/wp-content/plugins/kk-star-ratings/src/classes/Migration.php on line 14

Fatal error: require_once(): Failed opening required '/home/u9091456/public_html/wp-content/plugins/kk-star-ratings/src/classes/Stack.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/condoscojines/public_html/wp-content/plugins/kk-star-ratings/src/classes/Migration.php on line 14

**Comment by dcm20002000** [comment]
> > > > I try what "MrAnssaien" said and it is not working for me, adding this line: require_once 'Stack.php'; not fixed the issue, the plugin do not work and it is a pitty, I hope an update is coming soon, Thank you.
> > > 
> > > 
> > > Try using the full path to Stack.php.
> > > Example (from OP's error log): require_once '/home/u9091456/public_html/wp-content/plugins/kk-star-ratings/src/classes/Stack.php';
> > 
> > 
> > Thaks for your answer but I don`t understand, I go to Stack.php and then what?
> 
> You should go to Migration.php; not Stack.php. And then add:
> 
> `require_once 'Stack.php'; ` above `class Migration extends Stack`
> 
> If you still get the same error, it means, you should add the full path to Stack.php.

I try again with the full path and I get the error:

Warning: require_once(/home/u9091456/public_html/wp-content/plugins/kk-star-ratings/src/classes/Stack.php): failed to open stream: No such file or directory in /home/condoscojines/public_html/wp-content/plugins/kk-star-ratings/src/classes/Migration.php on line 14

Fatal error: require_once(): Failed opening required '/home/u9091456/public_html/wp-content/plugins/kk-star-ratings/src/classes/Stack.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/condoscojines/public_html/wp-content/plugins/kk-star-ratings/src/classes/Migration.php on line 14

**Comment by MrAnssaien** [comment]
Use this line instead: 

`require_once '/home/condoscojines/public_html/wp-content/plugins/kk-star-ratings/src/classes/Stack.php';`

It will work this time.

**Comment by dcm20002000** [comment]
> Use this line instead:
> 
> `require_once '/home/condoscojines/public_html/wp-content/plugins/kk-star-ratings/src/classes/Stack.php';`
> 
> It will work this time.

I did it and now I get this menssage: "kk Star Ratings tiene migraciones pendientes. Las valoraciones serán desactivadas hasta que las migraciones hayan finalizado."

**Comment by MrAnssaien** [comment]
> 
> 
> > Use this line instead:
> > `require_once '/home/condoscojines/public_html/wp-content/plugins/kk-star-ratings/src/classes/Stack.php';`
> > It will work this time.
> 
> I did it and now I get this menssage: "kk Star Ratings tiene migraciones pendientes. Las valoraciones serán desactivadas hasta que las migraciones hayan finalizado."

Just ignore/dismiss that message, because it has something to do with the author doing a full upgrade on their plugin. The plugin should work just fine for now. Buena suerte! :P

**Comment by dcm20002000** [comment]
> > > Use this line instead:
> > > `require_once '/home/condoscojines/public_html/wp-content/plugins/kk-star-ratings/src/classes/Stack.php';`
> > > It will work this time.
> > 
> > 
> > I did it and now I get this menssage: "kk Star Ratings tiene migraciones pendientes. Las valoraciones serán desactivadas hasta que las migraciones hayan finalizado."
> 
> Just ignore/dismiss that message, because it has something to do with the author doing a full upgrade on their plugin — check the README.md file. The plugin should work just fine for now. Buena suerte! :P

FINALLY WORKING!! Thanks so much!

**Comment by glu000** [comment]
> > > > Use this line instead:
> > > > `require_once '/home/condoscojines/public_html/wp-content/plugins/kk-star-ratings/src/classes/Stack.php';`
> > > > It will work this time.
> > > 
> > > 
> > > I did it and now I get this menssage: "kk Star Ratings tiene migraciones pendientes. Las valoraciones serán desactivadas hasta que las migraciones hayan finalizado."
> > 
> > 
> > Just ignore/dismiss that message, because it has something to do with the author doing a full upgrade on their plugin — check the README.md file. The plugin should work just fine for now. Buena suerte! :P
> 
> FINALLY WORKING!! Thanks so much!

Works for me, too

**Comment by kamalkhan** [comment]
Remove version 5.1.x in favour of 5.2.0 which should mitigate the issues.
